### ISSUE TITLE
Does not handle subdomains having their own DNS zone

### ISSUE THREAD

**Issue by frederickjh** [jpconver/dnsexit_dnshook#1]
Hi!
At DNSexit I have a domain and a subdomain setup as two separate DNS zones.  Lets call them **example.com** and **dev.example.com**. 
* **dev.example.com** points to a development server with test sites and is using a wildcard redirect to do this.
* **example.com** is my points to my business' website.

When I use `authenticator.sh` to deploy_challenge to DNSexit for ** dev.example.com** it matches **example.com** instead and places the DNS text record in the **example.com** DNS zone, but then queries the **dev.example.com** DNS zone for the the text record. This of course fails after the 300 seconds timeout.

I would try and submit a patch but my work with bash arrays in the past is very minimal as is my work with IFS. I am having a hard time wrapping my head around what the code does now.

It seems that it is starting with the top level domain and trying to match that then adding the domain name to it. It appears that in my use case this is where the match is made even though a subdomain is also given and there is a zone that matches it.

I think that the code needs to first try and get a full match for the full domain name if that does not work then it should fall back to the current code that tries to match the basename of the domain then place the record in the parent domain name zone.

Thanks for your time and help with this!
Frederick

**Comment by frederickjh** [comment]
I forgot to mention that in the list of domain names (zones) returned from DNSexit, **dev.example.com** comes before **example.com** in the list.

**Comment by frederickjh** [comment]
I commented out the `break;` on [this line](https://github.com/jpconver/dnsexit_dnshook/blob/master/base.sh#L44) to get it to work and match the subdomain too. Not sure if that is the best fix.

**Comment by jpconver** [comment]
Hi! I added some commits. I think this issue is fixed... :)

**Comment by frederickjh** [comment]
Resolved!
