### ISSUE TITLE
dnsexit login fails

### ISSUE THREAD

**Issue by dmmedia** [jpconver/dnsexit_dnshook#3]
Trying to update my certificates and looking at the logs and html files in the /tmp directory it seems that the whole process fails due to login failure. It seems that dnsexit has redesigned their page recently, though all the links seems to be correct. However I receive incomplete login response when I compare it with the headers in the browser. Script just does not receive 302 redirection and browser does. If you could provide step by step instructions of what to test or what to upload for investigation, I could try to do that to help to restore script functioning.

**Comment by jpconver** [comment]
Hi Denis!

Sorry I haven't had time to check the status of the plugin but I continue
using it. This is the first time you use it or it was working and it is
failing now?
Did you try to add a follow redirect flag to any of the curl/wget calls to
see if it continues?

Thanks!!

**Comment by dmmedia** [comment]
Thanks for response.

Plugin worked for some time, but now it is failing.

I tried to add -L flag for curl to follow redirect, but there is no change. Header returned does not contain any redirects and is a 200 OK response without body.

I tried to change post request to match the fields in the browser, but still no luck.

Dnsexit support team is not very responsive and helpful. Perhaps I should try manual refresh this time.

Did this plugin work for you in the past few days?

**Comment by jpconver** [comment]
Thanks Denis!

I will look into it as soon as I have some time. I'll keep you posted...

Best Regards
 David

**Comment by jpconver** [comment]
Hi! I think I've fixed it. I added also test script to verify that is working.

**Comment by dmmedia** [comment]
Thank you very much for your work. I was running out of time on this update, so I did it manually. I will update the script and let you know if it works next time in the end of October. Your script really helps with automating the procedures. Unfortunatelly I am lacking knowledge about using curl and was unable to help with fix.

**Comment by dmmedia** [comment]
Hi! I have checked the changes as promised and all the certificate renew flow works again. Just to let you know. Thank you for your time and work.

**Comment by jpconver** [comment]
Excellent!! Thank you!
