### ISSUE TITLE
DNSExit Redesign - No Domain names returned using testAuthenticator.sh

### ISSUE THREAD

**Issue by frederickjh** [jpconver/dnsexit_dnshook#4]
Hi!
Authentication was failing when I tried to updated a certificate. Going to the DNSExit site looks like they have made some more changes to the interface. Updated to the most recent version but `testAuthenticator.sh` returns an empty domainname.

Thanks for looking into this!
Frederick

**Comment by jpconver** [comment]
Thanks for the report, I'll switch to use the API instead of the web due that changes are huge and it will break every time there's is a change. I will keep you posted about the new version

**Comment by frederickjh** [comment]
I see that the DNS Exit API documentation has Let's Encrypt [examples](https://www.dnsexit.com/dns/dns-api/#example-lse). My domain's SSL certificate expires in a week on the 20th of January. Will need to figure out how to renew the certificate manually if you do not get time to fix it before then. Thanks!

**Comment by jpconver** [comment]
Finally have time to review this. Sorry for the delay. This new version use a base domain list provided by the user due that the API does not provide this information
